FROM node:20 AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm i 
COPY . .

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]