version: '3.8'

services:
  backend:
    image: ghcr.io/suj007web/backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DB_URL}
      - PORT=8000
    restart: always

  frontend:
    image: ghcr.io/suj007web/frontend:latest
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL} 
    depends_on:
      - backend
    restart: always
