version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env  
    depends_on:
      - backend
    restart: always
