version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:80"  
    depends_on:
      - backend
    restart: always
