version: '3.8'

services:
  backend:
    image: ghcr.io/suj007web/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: ghcr.io/suj007web/frontend:latest
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env  
    depends_on:
      - backend
    restart: always
