name: Build, Push Docker Images and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      # Build and push Backend
      - name: Build Backend Image
        working-directory: ./backend
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/backend:latest .

      - name: Push Backend Image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/backend:latest

      # Build and push Frontend
      - name: Build Frontend Image
        working-directory: ./frontend
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/frontend:latest .

      - name: Push Frontend Image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/frontend:latest

      # Deployment to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and run Backend
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/backend:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d -p 8000:8000 --name backend ghcr.io/${{ secrets.GHCR_USERNAME }}/backend:latest
            
            # Update and run Frontend
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/frontend:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d -p 5173:5173 --name frontend ghcr.io/${{ secrets.GHCR_USERNAME }}/frontend:latest