name: Build, Push Docker Images and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build and push Backend Image
      - name: Build and Push Backend Image
        working-directory: ./backend
        run: |
          docker build -t ghcr.io/${{ github.actor }}/backend:latest .
          docker push ghcr.io/${{ github.actor }}/backend:latest

      # Build and push Frontend Image
      - name: Build and Push Frontend Image
        working-directory: ./frontend
        run: |
          docker build -t ghcr.io/${{ github.actor }}/frontend:latest .
          docker push ghcr.io/${{ github.actor }}/frontend:latest

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GHCR_TOKEN
          script: |
            # Authenticate with GHCR
            echo "$GHCR_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull latest images
            docker-compose pull

            # Restart containers
            docker-compose down
            docker-compose up -d
