name: Build, Push Docker Images and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "$GHCR_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build and push Backend Image
      - name: Build and Push Backend Image
        working-directory: ./backend
        run: |
          docker build -t ghcr.io/${{ github.actor }}/backend:latest .
          docker push ghcr.io/${{ github.actor }}/backend:latest

      # Build and push Frontend Image
      - name: Build and Push Frontend Image
        working-directory: ./frontend
        run: |
          docker build -t ghcr.io/${{ github.actor }}/frontend:latest .
          docker push ghcr.io/${{ github.actor }}/frontend:latest

      # Copy docker-compose.yml to EC2
      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/my-app/"

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GHCR_TOKEN, DB_URL, BACKEND_URL
          script: |
            # Navigate to the directory with docker-compose.yml
            cd /home/ubuntu/my-app

            # Authenticate with GHCR
            echo "$GHCR_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull latest images and restart containers
            docker compose pull
            docker compose down
            docker compose up --no-cache --build -d